ozetleme_gorevi:
  description: >
    Verilen belgedeki ana noktaları çıkar ve kısa bir özet hazırla {input}
  expected_output: >
    Belgenin ana konularını öne çıkaran, madde madde düzenlenmiş bir özet.
  agent: ozetleyici

hukuki_analiz_gorevi:
  description: >
    Belgedeki hukuki riskleri ve olası sorunları belirle, analiz yap 
  expected_output: >
    Tespit edilen hukuki riskleri, olası etkilerini ve önemli hukuki hususları içeren detaylı bir rapor.
  agent: hukuk_analisti
